# Generated by Django 4.0.3 on 2022-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='profile-img.png', upload_to='Profile'),
        ),
    ]
