# Generated by Django 4.0.3 on 2022-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sector',
            field=models.CharField(choices=[('cleaning', 'cleaning'), ('car cleaning', 'car cleaning'), ('ac service', 'ac service')], max_length=50),
        ),
    ]
